export const stores = [
  {
    slug: "amazon",
    name: "Amazon",
    description:
      "Find the latest verified Amazon coupon codes, offers, and shopping discounts for Indian users.",
    couponsCount: 25,
    categories: ["Fashion", "Electronics", "Beauty", "Travel"],
  },
  {
    slug: "flipkart",
    name: "Flipkart",
    description:
      "Latest Flipkart offers, exclusive coupon codes, and verified shopping deals for India.",
    couponsCount: 18,
    categories: ["Electronics", "Fashion", "Mobiles"],
  },
];

export const coupons = [
  {
    slug: "amazon-80-off",
    storeSlug: "amazon",
    store: "Amazon",
    title: "Up to 80% OFF on Branded T-Shirts & Tops",
    code: "STYLE80",
    discount: "UP TO 80% OFF",
    description: "Extra 5% discount on selected cards.",
    terms:
      "Valid on selected branded T-shirts and tops. Applicable on eligible products only. Cannot be combined with certain promotions.",
    endDate: "Ends 30 Sept",
    bankOffer: "20% Flat Discount on ICICI Card",
    usedToday: 124,
    verified: true,
    best: true,
    category: "Fashion",
    users: "New users only",
    hasCode: true,
    affiliateUrl: "https://www.amazon.in/",
  },
  {
    slug: "amazon-flat-500",
    storeSlug: "amazon",
    store: "Amazon",
    title: "Flat ₹500 OFF on orders above ₹2,999",
    code: "",
    discount: "₹500 OFF",
    description: "Extra discount available on prepaid orders.",
    terms:
      "Offer valid on selected orders above ₹2,999. Bank or wallet restrictions may apply. Final discount shown at checkout.",
    endDate: "Ends 28 Sept",
    bankOffer: "10% Flat Discount on HDFC Card",
    usedToday: 89,
    verified: true,
    best: false,
    category: "Electronics",
    users: "All users",
    hasCode: false,
    affiliateUrl: "https://www.amazon.in/",
  },
  {
    slug: "flipkart-mobile-sale",
    storeSlug: "flipkart",
    store: "Flipkart",
    title: "Save 40% on Mobile Accessories",
    code: "MOBILE40",
    discount: "40% OFF",
    description: "Limited-time mobile accessories deal.",
    terms:
      "Valid on selected accessories only. Stock may be limited. Offer may expire early without notice.",
    endDate: "Ends 02 Oct",
    bankOffer: "15% Instant Discount on Axis Card",
    usedToday: 67,
    verified: true,
    best: true,
    category: "Electronics",
    users: "All users",
    hasCode: true,
    affiliateUrl: "https://www.flipkart.com/",
  },
];